#GET in your browser:
# Code Verifier: teste123
# Code Challenge: teste123
# Obs mudar o method para s256 (SHA-256)
http://localhost:8081/oauth/authorize?response_type=code&client_id=food-analytics&state=abc&redirect_uri=http://aplicacao-cliente&code_challeng_method=plain&code_challeng=teste123


#sha-256
# https://tonyxu-io.github.io/pkce-generator/
#GET in your browser:
# Code Verifier: teste123
# Code Challenge com base64 e sha256 base64url(sha256(teste123)): KJFg2w2fOfmuF1TE7JwW-QtQ4y4JxftUga5kKz09GjY
http://localhost:8081/oauth/authorize?response_type=code&client_id=food-analytics&state=abc&redirect_uri=http://aplicacao-cliente&code_challeng_method=s256&code_challeng=KJFg2w2fOfmuF1TE7JwW-QtQ4y4JxftUga5kKz09GjY


###
POST {{base_auth_host}}/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: {{basic_auth_credentials}}

grant_type=authorization_code&redirect_uri=http://aplicacao-cliente&code_verifier=teste123&code=kUSmN8er

> {%
    client.global.set("auth_token", response.body.access_token);
    client.global.set("auth_refresh_token", response.body.refresh_token);
%}

###
POST {{base_auth_host}}/oauth/introspect
Content-Type: application/x-www-form-urlencoded
Authorization: {{basic_auth_credentials}}

token={{auth_token}}

