#GET in your browser:
http://localhost:8081/oauth/authorize?response_type=code&client_id=food-analytics&state=abc&redirect_uri=http://aplicacao-cliente

###
POST {{base_auth_host}}/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: {{basic_auth_credentials}}

grant_type=authorization_code&redirect_uri=http://aplicacao-cliente&code=bzUkKc

> {%
    client.global.set("auth_token", response.body.access_token);
    client.global.set("auth_refresh_token", response.body.refresh_token);
%}

###
POST {{base_auth_host}}/oauth/introspect
Content-Type: application/x-www-form-urlencoded
Authorization: {{basic_auth_credentials}}

token={{auth_token}}

