###
POST {{base_auth_host}}/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: {{basic_auth_credentials}}

username=manoel.loja@gmail.com&password=123&grant_type=password

> {%
    client.global.set("auth_token", response.body.access_token);
    client.global.set("auth_refresh_token", response.body.refresh_token);
%}

###
POST {{base_auth_host}}/oauth/introspect
Content-Type: application/x-www-form-urlencoded
Authorization: {{basic_auth_credentials}}
Accept: */*

token={{auth_token}}

###
POST {{base_auth_host}}/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: {{basic_auth_credentials}}

refresh_token={{auth_refresh_token}}&grant_type=refresh_token

> {%
    client.global.set("auth_token", response.body.access_token);
    client.global.set("auth_refresh_token", response.body.refresh_token);
%}
