POST http://localhost:8081/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic ZmF0dXJhbWVudG86ZmF0dXJhbWVudG8xMjM=

grant_type=client_credentials

###

POST http://localhost:8081/oauth/introspect
Content-Type: application/x-www-form-urlencoded
Authorization: Basic ZmF0dXJhbWVudG86ZmF0dXJhbWVudG8xMjM=

token=LMB-J_raVpXJAKCyhd9Mi9yNj9o

###
