POST http://localhost:8081/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic Zm9vZC13ZWI6d2ViMTIz

username=food-user&password=123456&grant_type=password

###

POST http://localhost:8081/oauth/introspect
Content-Type: application/x-www-form-urlencoded
Authorization: Basic Zm9vZC13ZWI6d2ViMTIz

token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDMwMzk1MzgsInVzZXJfbmFtZSI6ImZvb2QtdXNlciIsImF1dGhvcml0aWVzIjpbIlJPTEVfQURNSU4iXSwianRpIjoiWXVBSTBGRHZEVi1qUkFiVTBGTW5KOG1NcXZJIiwiY2xpZW50X2lkIjoiZm9vZC13ZWIiLCJzY29wZSI6WyJ3cml0ZSIsInJlYWQiXX0.f8lSo3FADqn1OORrguWW9MNT2OcNormrmVY9-xCgOao

###

POST http://localhost:8081/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic Zm9vZC13ZWI6d2ViMTIz

refresh_token=DRVHbUlSQ_ZNo6pbjChY0j_t_zA&grant_type=refresh_token

###