POST http://localhost:8081/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic Zm9vZC13ZWI6d2ViMTIz

username=jose.aux@food.com&password=123&grant_type=password

###

POST http://localhost:8081/oauth/introspect
Content-Type: application/x-www-form-urlencoded
Authorization: Basic Zm9vZC13ZWI6d2ViMTIz

token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2MDMwNTM0NzEsInVzZXJfbmFtZSI6Impvc2UuYXV4QGZvb2QuY29tIiwianRpIjoiOGk4Ull1VkpucG1wTlpIU2FjOE5wdVlIYUZJIiwiY2xpZW50X2lkIjoiZm9vZC13ZWIiLCJzY29wZSI6WyJ3cml0ZSIsInJlYWQiXX0.kIlpDbwkzYmUqGaVCN1pEQX4NNJS7QdGqEqRwqPz7YcLhOC1kSpJgpSU4hdvmTrdy6AeBHflF78FD1fiJSWQUDyjfjAacNrT2Uw2oLlWfojR_lB16qiJRzHBS0oWJ6Dp_mciJXVo7N1c9_puTku1-4QU0VMe32vNXuCnG6ARf35KNbEjCUcAqcj6sSxpnj3Ff6C7vZYUZTU_ecpaGY_1XQVBg9Nezw4TBjcetuiRRS2qVOyw1BMoD9dv6mXFIT2s-fMax40UD29BxtSvWz2poQtfu9JwLgsdYOqBQctawmTh0pP7WgfUrIeKC4GoWDxgqI3btGknr3r4x4kFKLNyPQ

###

POST http://localhost:8081/oauth/token
Content-Type: application/x-www-form-urlencoded
Authorization: Basic Zm9vZC13ZWI6d2ViMTIz

refresh_token=DRVHbUlSQ_ZNo6pbjChY0j_t_zA&grant_type=refresh_token

###